CREATE TABLE DEPARTAMENTO (
	ID INT NOT NULL IDENTITY,
	DEPARTAMENTO VARCHAR(255) NOT NULL
);

CREATE TABLE CARGO(
	ID INT NOT NULL IDENTITY,
	CARGO VARCHAR(255) NOT NULL,
	ID_DEPARTAMENTO INT NOT NULL,
	 CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID) ON DELETE CASCADE
);

CREATE TABLE ENDERECO(
	ID INT NOT NULL IDENTITY,
	LOGRADOURO VARCHAR(255) NOT NULL,
	NUMERO INT NOT NULL,
	COMPLEMENTO VARCHAR(255),
	CIDADE VARCHAR(255) NOT NULL,
	BAIRRO VARCHAR(255) NOT NULL,
	ESTADO VARCHAR(255) NOT NULL
);

CREATE TABLE FUNCIONARIO(
	ID INT NOT NULL IDENTITY,
	ID_CARGO INT NOT NULL,
	ID_ENDERECO INT NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	SALARIO DOUBLE NOT NULL,
	DATA_ENTRADA DATE NOT NULL,
	DATA_SAIDA DATE,
	 CONSTRAINT FK_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID),		
	 CONSTRAINT FK_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID)
);